export const homeObjOne = {
	id: 'about',
	lightBg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Premium Bank',
	headline: 'Unlimited transactions with zero fees',
	description: 'get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
	buttonLabel: 'Get started',
	imgStart: false,
	img: require('../../images/svg-1.svg').default,
	alt: 'Car',
	dark: true,
	primary: true,
	darkText: false,
}

export const homeObjTwo = {
	id: 'roadmap',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Here is the roadmap',
	headline: 'Unlimited transactions with zero fees',
	description: 'get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
	buttonLabel: 'Get started',
	imgStart: true,
	img: require('../../images/svg-2.svg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
}

export const homeObjThree = {
	id: 'buy',
	lightBg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Premium Bank',
	headline: 'Unlimited transactions with zero fees',
	description: 'get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
	buttonLabel: 'Get started',
	imgStart: false,
	img: require('../../images/svg-3.svg').default,
	alt: 'Car',
	dark: true,
	primary: true,
	darkText: false,
}